/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.otraves2025;

/**
 *
 * @author USER
 */
public class NuevaInterfas extends javax.swing.JFrame {

    /**
     * Creates new form Ninterfaz
     */
    public NuevaInterfas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgServicios = new javax.swing.ButtonGroup();
        btgAsistencia = new javax.swing.ButtonGroup();
        lblSRPPE = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblCategoriaP = new javax.swing.JLabel();
        ckbxAlmuerzo = new javax.swing.JCheckBox();
        ckbxTransporte = new javax.swing.JCheckBox();
        ckbxMaterialA = new javax.swing.JCheckBox();
        rbtManana = new javax.swing.JRadioButton();
        rbtTarde = new javax.swing.JRadioButton();
        btnRegistrarP = new javax.swing.JButton();
        btnMostrarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSRPPE.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSRPPE.setText("SISTEMA DE REGISTRO DE PARTICIPANTES PARA UN EVENTO");

        lblNombreP.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        lblNombreP.setText("NOMBRE PARTICIPANTE :");

        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });

        cbxCategoria.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "PROFESIONAL", "INVITADO", "ESPECIAL" }));

        lblCategoriaP.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        lblCategoriaP.setText("CATEGORIA DE PARTICIPANTE");

        btgServicios.add(ckbxAlmuerzo);
        ckbxAlmuerzo.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        ckbxAlmuerzo.setText("ALMUERZO");
        ckbxAlmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxAlmuerzoActionPerformed(evt);
            }
        });

        btgServicios.add(ckbxTransporte);
        ckbxTransporte.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        ckbxTransporte.setText("TRANSPORTE");

        btgServicios.add(ckbxMaterialA);
        ckbxMaterialA.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        ckbxMaterialA.setText("MATERIAL DE APOYO");
        ckbxMaterialA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxMaterialAActionPerformed(evt);
            }
        });

        btgAsistencia.add(rbtManana);
        rbtManana.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        rbtManana.setText("MAÑANA");
        rbtManana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMananaActionPerformed(evt);
            }
        });

        btgAsistencia.add(rbtTarde);
        rbtTarde.setFont(new java.awt.Font("Harrington", 3, 12)); // NOI18N
        rbtTarde.setText("TARDE");

        btnRegistrarP.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnRegistrarP.setText("REGISTRAR PARTICIPANTE");
        btnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPActionPerformed(evt);
            }
        });

        btnMostrarR.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnMostrarR.setText("MOSTRAR REGISTRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSRPPE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreP)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbxAlmuerzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(ckbxTransporte)
                        .addGap(30, 30, 30)
                        .addComponent(ckbxMaterialA)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarP)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategoriaP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(rbtManana)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtTarde)
                    .addComponent(btnMostrarR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSRPPE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreP)
                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaP)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxAlmuerzo)
                    .addComponent(ckbxTransporte)
                    .addComponent(ckbxMaterialA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtManana)
                    .addComponent(rbtTarde))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarP)
                    .addComponent(btnMostrarR))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void ckbxAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxAlmuerzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxAlmuerzoActionPerformed

    private void ckbxMaterialAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxMaterialAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxMaterialAActionPerformed

    private void btnRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPActionPerformed
        String nombre = txtNombreP.getText();
        String categoria = (String) cbxCategoria.getSelectedItem();
        String almuerzo =  Boolean.toString(ckbxAlmuerzo.isSelected());
        String transporte = Boolean.toString(ckbxTransporte.isSelected());
        String material = Boolean.toString(ckbxMaterialA.isSelected());
        Boolean turnoManana= rbtManana.isSelected();
        Boolean turnoTarde = rbtTarde.isSelected();
        String turno ="";
        if (turnoManana){
        turno ="Mañana";
        }else
        if (turnoTarde){
        turno="Tarde";}         // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPActionPerformed

    private void rbtMananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMananaActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAsistencia;
    private javax.swing.ButtonGroup btgServicios;
    private javax.swing.JButton btnMostrarR;
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JCheckBox ckbxAlmuerzo;
    private javax.swing.JCheckBox ckbxMaterialA;
    private javax.swing.JCheckBox ckbxTransporte;
    private javax.swing.JLabel lblCategoriaP;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblSRPPE;
    private javax.swing.JRadioButton rbtManana;
    private javax.swing.JRadioButton rbtTarde;
    private javax.swing.JTextField txtNombreP;
    // End of variables declaration//GEN-END:variables
}
